version: '3'
services:
  database:
    image: 'postgres:latest'

    ports:
      - 5435:5435

    volumes:
      - ./db-data/:/var/lib/postgresql/data/

    env_file:
      - .env

  jpa:
    database: POSTGRESQL
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
      format_sql: true
      ddl-auto: create

